### ISSUE TITLE
PoissonRecon repo not found

### ISSUE THREAD

**Issue by XkRecarens** [StandardCyborg/StandardCyborgSDK#1]
Installing PoissonRecon (9.011)

[!] Error installing PoissonRecon
[!] /usr/bin/git clone git@github.com:StandardCyborg/PoissonRecon.git /var/folders/wx/r0s7cmv54ys7r22ch2ft4r4h0000gn/T/d20220819-74502-ojohs --template= --single-branch --depth 1 --branch xcodeproj

Cloning into '/var/folders/wx/r0s7cmv54ys7r22ch2ft4r4h0000gn/T/d20220819-74502-ojohs'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

**Comment by XkRecarens** [comment]
I changed the repo for this one [mkazhdan/PoissonRecon](https://github.com/mkazhdan/PoissonRecon), last version, but then some classes are missing like MeshingOperation.h

**Comment by aaptho** [comment]
@XkRecarens thank you for the report! We’re using a fork of that library wherein we added those classes.

Just made it public, can you try again? Our changes are on the branch `xcodeproj`
