### ISSUE TITLE
Wrong mapped texture in .obj export?

### ISSUE THREAD

**Issue by karloscampus** [StandardCyborg/StandardCyborgSDK#10]
First of all, thank you for the Open Source Project, it is a really great and innovative library! 
Unfortunately I have problems loading the zip (.obj export) into Blender. I have the feeling that the texture is not mapped correctly to the surface.
I only use the Example project and only run scene.mesh?.writeToOBJZip(atPath: documentsURL.appendingPathComponent("objzip").path) after creating the scene.
Loaded in Blender an MeshLab looks like:
![untitled](https://user-images.githubusercontent.com/5212245/231496415-5667ce97-1a6a-4b00-96ca-6f75b21e55ad.png)
am I doing something wrong?
Thanks in advance!

**Comment by aaptho** [comment]
Hah, looks like an art piece!

It’s possible the uv map coordinates are inverted. Are you able to flip them while importing into Blender?
Or if you want to try inverting them in code, remove the `1.0 - ` from line `SCMesh+FileIO.mm:117`. (At least that’s where I think this code lives, it’s been a few years).

**Comment by karloscampus** [comment]
that is right. I flipped the output texture vertically and it matches! Thanks!!

**Comment by aaptho** [comment]
Great, glad it worked! Would you mind submitting a PR for that change?

The other file format export functions do not invert the value, so I don’t see why we should invert it here.

**Comment by aaptho** [comment]
Fixed with commit `0689b0`
