### ISSUE TITLE
Pod issue

### ISSUE THREAD

**Issue by Sarvjeetsh** [StandardCyborg/StandardCyborgSDK#11]
Hii while installing pod files it says acces denied, can you help me with that thanks..

**Comment by aaptho** [comment]
Can you please provide the full output from this error message, and exactly what command you ran?

**Comment by Sarvjeetsh** [comment]
I ran pos install command in terminal and this is the error I am getting

Pre-downloading: `PoissonRecon` from `git@github.com:StandardCyborg/PoissonRecon.git`, commit `9f30316c1b247736654652c72e06b3f0db2e79ed`

[!] Error installing PoissonRecon
[!] Failed to download 'PoissonRecon': [!] /usr/bin/git clone git@github.com:StandardCyborg/PoissonRecon.git /var/folders/fg/rls0p68d5vl423_2xgs461900000gn/T/d20230513-7177-kl3ahf --template=

Cloning into '/var/folders/fg/rls0p68d5vl423_2xgs461900000gn/T/d20230513-7177-kl3ahf'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by aaptho** [comment]
Strange, that is a standard GitHub repo spec. Are you able to access this repo on the web?
https://github.com/StandardCyborg/PoissonRecon/tree/xcodeproj

**Comment by Sarvjeetsh** [comment]
yes, I can access this repo

**Comment by stadarz** [comment]
Same problem here. @Sarvjeetsh Have you found a solution? Thanks.

**Comment by stadarz** [comment]
@Sarvjeetsh Managed to fix it by setting up the ssh on my mac (obviously :) ) and deleting the podfile.lock. Afterwards running pod install worked.

**Comment by Sarvjeetsh** [comment]
@stadarz  thank you very much, will try your solution. Also you can get depth data directly from ARFront camera configuration using frame.capturedDepthData?.depthDataMap which can give you depth data. I started from scratch lol
