### ISSUE TITLE
run to build framework - crc32.cpp and writteUSDZCompatibleZip.cpp - failed to open diagnostic file

### ISSUE THREAD

**Issue by martintseng** [StandardCyborg/StandardCyborgSDK#3]
Hi there,

I am trying to simply build the framework successfully, and I ran into this error.

<img width="896" alt="Screen Shot 2022-08-26 at 12 08 41 PM" src="https://user-images.githubusercontent.com/28665884/186947857-2afd4ea9-e327-4a85-8b7f-98ac1ff62b60.png">

Here are the steps I took:
1- I cloned the git. (and verified that git lfs was installed)
2- ran this command in terminal: ./install-dependencies.sh
3- opened StandardCyborgSDK.xcworkspace
4- changed the sign in teams.
5- Clicked on build.

Was I supposed to take some other steps for this? I apologize in advance if the answer may seem to be obvious!

Thanks,

Martin

**Comment by daver234** [comment]
FYI I did the same install steps but found errors.  My work around was to download again into a new folder, twice, and the third time after the install it worked.

**Comment by martintseng** [comment]
> FYI I did the same install steps but found errors. My work around was to download again into a new folder, twice, and the third time after the install it worked.

well, it did fix more of the errors. Only one error that I can't fix:
<img width="836" alt="image" src="https://user-images.githubusercontent.com/28665884/187524712-7806c714-9b6d-4300-9e80-ec81d279acf8.png">

Just out of curiosity, what exactly do you mean by download into a folder, twice, and third time?

**Comment by daver234** [comment]
I meant just new installs in different folders rather than re-install into the same folder.  I did three separate downloads and the third worked for some reason.  The other two it wasn't installing all the large files, I assume.

**Comment by Yaroslav-Symonenko** [comment]
@daver234 , I was facing the same issue as @martintseng , but your solution didn't work for me either.

@martintseng , try to do the next steps:
   1) Since xCode couldn't find compiler cache at the specific place (see logs: _..../DependenciesSupport/ccache-clang: line 7: /opt/homebrew/bin/ccache: No such file or directory_), do that yourself. In terminal run 
    _**"command -v ccache"**_
, so you'll get the actual path it was installed at. In my case it is -
    _**"/usr/local/bin/ccache"**_
   2) Go to the <StandardCyborgSDK project folder>/DependenciesSupport/, then open "ccache-lang" with text editor and change the path at the latest line 
    **_"exec /opt/homebrew/bin/ccache clang "$@""_**
to 
    _**"exec /usr/local/bin/ccache clang "$@""**_
   3) Repeat step 2 for _**"ccache-clang++"**_ file
   4) Try to build again - it helped me.

**Comment by martintseng** [comment]
Someone helped me and it worked! Here is what worked for me as well:

Since xCode couldn't find compiler cache at the specific place (see logs: ..../DependenciesSupport/ccache-clang: line 7: /opt/homebrew/bin/ccache: No such file or directory), do that yourself. In terminal run
"command -v ccache", so you'll get the actual path it was installed at. In my case it is - "/usr/local/bin/ccache"

Go to the /DependenciesSupport/, then open "ccache-lang" with text editor and change the path at the latest line
"exec /opt/homebrew/bin/ccache clang "$@"" to "exec /usr/local/bin/ccache clang "$@""

Repeat step 2 for "ccache-clang++" file

Try to build again - it helped me.

**Comment by aaptho** [comment]
Looks like Homebrew installs binaries to different paths depending on whether you’re on an M1 Mac vs on Intel. I just pushed a fix that will make it look in both places, and fall back to plain old clang if neither is found.
