### ISSUE TITLE
how to operate the delay of reconstruction?

### ISSUE THREAD

**Issue by sxy771** [StandardCyborg/StandardCyborgSDK#7]
I want to revise the delay of scanning system.
I mean I want to reconstruct the frame every 5secs but, now it's done every 0.033...secs.
Who knows that how to set up the reconstruction time?

**Comment by aaptho** [comment]
Easiest would be to duplicate ScanningViewController into your own project and modify that.

In `cameraDidOutput()`, you should store the arguments into instance variables, then create a timer that calls `_reconstructionManager.accumulate()` with those values every 5 seconds.
